### ISSUE TITLE
[Discussion] Percentile Ranking

### ISSUE THREAD

**Issue by tcaruth** [chainreactionboom/pokemon-sleep-grader#5]
After reviewing the code, I found everything pretty understandable. I was curious, do you think the percentile ranking is misleading? It appears to be calculating best possible across any pokemon; I expected it to be the best for my specific species (ranking my nature and subskills against the best possible choices).

**Comment by w0jnar** [comment]
Admittedly, just a contributor to this repo, so I don't get notifications here, but saw your issue and wanted to comment in case this helps.

The algorithm is relatively simplistic when comparing pokemon because at the end of the day, it is really only comparing specialty to best nature/subskill. So to clarify on your question, it isn't useful for comparing "any pokemon" to "any pokemon" but it is useful for comparing "any [berry|ingredient|skill]" pokemon to any pokemon of the same specialty.

So to be clear, it isn't going into the specifics of a specific species' base helping speed or even main skill itself, but it is comparing the specialty of the pokemon you chose in combination with its nature and subskills to see if it is an ideal combination. Which means it is useful for comparing 2 bulbasaur as an example, as they are both trying to reach an ideal for ingredient specialty pokemon, but it only looking so far as specialty, nature, and subskills.

To add to that, you could have a 100 of any species, not just a specific specialty, but due to how the scoring works, there are multiple combinations of natures/subskills that could be a 100, depending on that specialty.
@chainreactionboom provided this Gist as a Reddit comment for the best combinations for each specialty according to this rating system:
https://gist.github.com/chainreactionboom/538a057f1ea113ccf4b84d37c455f267


In terms of the actual score/weighs, it came out of this thread/the Sleep Mathcord collaborating data into a rating system:
https://www.reddit.com/r/PokemonSleep/comments/16eiidw/i_made_a_pok%C3%A9mon_sleep_rating_discord_bot/

Code here for the discord bot which also includes more details on the ratings break down:
https://github.com/Alfendi/Pokemon-Sleep-Rater

This repo is mainly just a front end implementation using the same algorithm as the discord bot.

**Comment by chainreactionboom** [comment]
Thanks for answering this question @w0jnar with great details. (I rarely check this Github since this is my alt account 😃).

> It appears to be calculating best possible across any pokemon; I expected it to be the best for my specific species (ranking my nature and subskills against the best possible choices).

This is not true, check this specific part of the code
https://github.com/chainreactionboom/pokemon-sleep-grader/blob/main/data.js#L92-L127

The percentile values are different depending on the Pokemon speciality.
